<Project Sdk="MSTest.Sdk/4.0.2">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Observatory.Sample/**/*.cs" />
    <ProjectReference Include="Observatory.Sample/Observatory.Sample.csproj" />
  </ItemGroup>

</Project>
